require 'simplecov'
SimpleCov.start
require 'minitest/autorun'
require 'minitest/pride'
require 'mocha/minitest'
require './modules/key_offset_helper'
require './lib/keys'
require './lib/offset'
require './lib/enigma'
require './lib/encryptor.rb'
require 'pry'
